### ISSUE TITLE
Register Device and Set key through a single call to the APIs

### ISSUE THREAD

**Issue by mfinley3** [brocaar/chirpstack-application-server#325]
### Is this a bug or a feature request?
feature request

### Request 
I would like to be able to register/update a device and set a key in a single call to the API. 
This request was mentioned in #276 as well. 

I am heavily relying on the API for device registrations. Being able to register a device and set a key in a single call would not only make the tooling I have less complex, but it would reduce the chances of a partially registered device (one that has everything but the keys set). 

Similar for `PUT /api/devices/{device.dev_eui}`, it would be nice to be able to update the entire device, keys included, in a single call.

### What version are your using?
2.5.1

**Comment by brocaar** [comment]
> it would reduce the chances of a partially registered device (one that has everything but the keys set).

Please note that this could be a valid situation, when using an external Join Server.
