### ISSUE TITLE
Create a rolled-up dashboard summary

### ISSUE THREAD

**Issue by KarthikSubramanian2** [brocaar/chirpstack-application-server#335]
### Is this a bug or a feature request?
Feature request
### What did you expect?
Visualize a rolled up summary of all the gateways and devices
### What version are your using?
2.6.1

This is just an idea. It would be nice to see a summary of the following in a `health` dashboard.

 - Total gateways (Live, offline) 
 - Total devices (Live, offline - If a device hasn't sent an uplink in X days)

**Comment by brocaar** [comment]
This has been implemented in the latest releases.
