### ISSUE TITLE
Copy clipboard Hex keys

### ISSUE THREAD

**Issue by wolftrax5** [brocaar/chirpstack-application-server#364]
### Is this a bug or a feature request?
Feature
### What did you expect?
A button to Copy the Activation Keys to the preferred format.
### What happened?
As a user when the Activation Keys are set on a device, need to program a Lora device with that Keys on (ABP or OTAA) and need to paste the same key to the device work,
For example if the key Application session key is 
`f3 43 d2 01 d5 33 1d 0b a5 54 1b 4c fa a4 4d e7` 
some formats when i use to program the lora devices are 

- Array Hex: `[0xF3, 0x43, 0xD2, 0x01, 0xD5, 0x33, 0x1D, 0x0B, 0xA5, 0x54, 0x1B, 0x4C, 0xFA, 0xA4, 0x4D, 0xE7]`
- with out space : `F343D201D5331D0BA5541B4CFAA44DE7`

### What version are your using?
3.3.0

**Comment by brocaar** [comment]
This has been merged.
