### ISSUE TITLE
CID not implemented: PackageVersionReq

### ISSUE THREAD

**Issue by alexdirty** [brocaar/chirpstack-application-server#370]
### Is this a bug or a feature request?
Bug request.

### What did you expect?
RPC  success.

### What happened?

RPC error:
code = Internal desc = handle remote fragmentation session command error: CID not implemented: PackageVersionReq" grpc.code=Internal grpc.method=HandleUplinkData grpc.request.deadline="2019-09-30T16:17:30+03:00" grpc.service=as.ApplicationServerService grpc.start_time="2019-09-30

### What version are your using?
3.3.1

### How can your issue be reproduced?
Get UP message on frport 201 from device.

### Could you share your log output?
`30 16:17:29 loraservers lora-app-server[18237]: time="2019-09-30T16:17:29+03:00" level=error msg="finished unary call with code Internal" error="rpc error: code = Internal desc = handle remote fragmentation session command error: CID not implemented: PackageVersionReq" grpc.code=Internal grpc.method=HandleUplinkData grpc.request.deadline="2019-09-30T16:17:30+03:00" grpc.service=as.ApplicationServerService grpc.start_time="2019-09-30

Hello!

A similar problem with the use of ports FUOTA as in the issue https://github.com/brocaar/lora-app-server/issues/362

@brocaar, I have a similar problem, but with port 201 and error "CID  not implemented: **PackageVersionReq**"

We use a device that is implemented on the specification of LoRaWAN v1.0.1. And this device uses port 201.

Because the specification "LoRaWAN Fragmented Data Block Transport v1.0.0 Specification" is optional, then only those devices that transmit large amounts of data should support it. Therefore, the device we use does not support it.

Specification "LoRaWAN Fragmented Data Block Transport v1.0.0"  is in addition to the specifications of the MAC layer LoRaWAN v1.0.2 and v1.1.

The device we use supports the specification of the MAC level LoRaWAN v1.0.1.

lora-app-server supporting the specification LoRaWAN v1.0.2 and v1.1 must support the operation of devices v1.0.0 and v1.0.1.

Changing the LoRaWAN MAC version in the Device Profile does not produce a result.

Can you fix it or help solve the problem?

`30 16:17:29 loraservers lora-app-server[18237]: time="2019-09-30T16:17:29+03:00" level=error msg="finished unary call with code Internal" error="rpc error: code = Internal desc = handle remote fragmentation session command error: CID not implemented: PackageVersionReq" grpc.code=Internal grpc.method=HandleUplinkData grpc.request.deadline="2019-09-30T16:17:30+03:00" grpc.service=as.ApplicationServerService grpc.start_time="2019-09-30T16:17:29+03:00" grpc.time_ms=4.841 peer.address="127.0.0.1:49572" span.kind=server system=grpc`

_Originally posted by @alexdirty in https://github.com/brocaar/lora-app-server/issues/362#issuecomment-536991038_

**Comment by sagar-patel-sls** [comment]
Hii, we have also faced the same issue

```
time="2020-01-28T18:05:09+05:30" level=info msg="device-session saved" dev_addr=00abcdef dev_eui=xxxxxxxxxxxxxxxx
time="2020-01-28T18:05:09+05:30" level=error msg="finished client unary call" error="rpc error: code = Internal desc = handle clocksync command error: CID not implemented: PackageVersionReq" grpc.code=Internal grpc.method=HandleUplinkData grpc.service=as.ApplicationServerService grpc.time_ms=6.165 span.kind=client system=grpc
time="2020-01-28T18:05:09+05:30" level=error msg="publish uplink data to application-server error" error="rpc error: code = Internal desc = handle clocksync command error: CID not implemented: PackageVersionReq"
time="2020-01-28T18:05:09+05:30" level=info msg="adr request added to mac-command queue" dev_eui=xxxxxxxxxxxxxxxx dr=5 nb_trans=1 req_dr=5 req_nb_trans=1 req_tx_power_idx=4 tx_power=2
time="2020-01-28T18:05:09+05:30" level=info msg="pending mac-command block set" cid=LinkADRReq commands=1 dev_eui=xxxxxxxxxxxxxxxx
```
