### ISSUE TITLE
Add Single Sign-on

### ISSUE THREAD

**Issue by skeff839** [brocaar/chirpstack-application-server#372]
### Is this a bug or a feature request?
Feature request
### What did you expect?
A single sign-on for the application server login.
With Microsoft Azure, Google Cloud Platform and Amazon Web Services.

**Comment by JohnRoesler** [comment]
SAML integration would be a great feature so that we don't have to maintain separate usernames/passwords in the CAS.

**Comment by brocaar** [comment]
@skeff839 @JohnRoesler  OpenID Connect has been implemented by the above commit.

**Comment by JohnRoesler** [comment]
Thank you. I will add it to my to dos to test this out
