### ISSUE TITLE
Add gateway's additional meta-data access from lora-app-server API

### ISSUE THREAD

**Issue by raphaelruet** [brocaar/chirpstack-application-server#377]
### Is this a bug or a feature request?

Feature request

### What did you expect?

Be able to have access, via lora-app-server api, to the additional static & dynamic meta data added to the gateway's stats messages (configured in the lora-gateway-bridge configuration)

### What happened?

The additional meta-data are pushed to the gateway's MQTT stats topic but not accessible from the lora-app-server web-interface/api.

### What version are your using?

lora-gateway-bridge v3.3.0
lora-server v3.3.0
lora-app-server v3.4.0

### How can your issue be reproduced?

Add dynamic or static meta-data to be pushed with stats messages in the lora-gateway-bridge configuration and try to fetch those meta-data from the `api/gateways/{gateway-ip}/stats` api route.

**Comment by guftall** [comment]
Thanks for implementation, displaying gateway ip address in web will definitely save people's time.
