### ISSUE TITLE
LoRaWAN1.1 OTAA app session key maybe wrong

### ISSUE THREAD

**Issue by wwx0715** [brocaar/chirpstack-application-server#382]
### Is this a bug or a feature request?
Maybe a bug
### What did you expect?
Use right app session key through OTAA join when using LoRaWAN1.1
### What happened?
app session is not right at server(caculate manually according to LoRaWAN spec1.1 and node caculate are same), but all network session keys are all right
### What version are your using?
chirpstack-gateway-bridge 3.4.1
chirpstack-network-server 3.4.1
chirpstack-application-server 3.5.1
### How can your issue be reproduced?
this problem always exist. just normally join through OTAA
### Could you share your log output?
I tried to degug this problem, and found the app session key maybe caculated using appkey 00000000000000000000000000000000.
I tried to fix this problem using bellow patch:

--- a/internal/api/js/join_server.go
+++ b/internal/api/js/join_server.go
@@ -103,6 +103,7 @@ func getHandler(conf config.Config) (http.Handler, error) {
                        return joinserver.DeviceKeys{
                                DevEUI:    dk.DevEUI,
                                NwkKey:    dk.NwkKey,
+                              AppKey:    dk.AppKey,
                                JoinNonce: dk.JoinNonce,
                        }, nil
                 },

please confirm this problem or I misunderstand.

**Comment by brocaar** [comment]
Thanks for reporting and sorry for the delay. The above commit fixes the issue + adds a test for this.
