### ISSUE TITLE
API bug POST /api/multicast-groups/{multicast_group_id}/devices

### ISSUE THREAD

**Issue by geniv** [brocaar/chirpstack-application-server#387]
### Is this a bug or a feature request?
bug: yes

### What did you expect?
I expected exception number 400

### What happened?
I add device XY to multicast group A (OK) and after I add same device XY to multicast group B (OK->but should by FAIL) => that is total fail, one device has one multicast settings.

### What version are your using?
api version: 1.0.0

### How can your issue be reproduced?
create device XY, and create two multicast. Add device to first multicast. And then add same device XY to second multicast.

**Comment by brocaar** [comment]
Technically a device can be assigned to multiple multicast-groups. The device can identify the multicast-group based on DevAddr / session-key.

This is also implemented in the Remote Multicast Setup specification.

**Comment by geniv** [comment]
OK, thanks
