### ISSUE TITLE
go.mod regenerat the dependencies that have been deleted

### ISSUE THREAD

**Issue by alfonzodi** [brocaar/chirpstack-application-server#391]
Hi, 

 I'm trying to compile the chirpstack-application-server with sources files , and it's work, my next step is to edit the LORAWAN package and  compiling the server with my version of lorawanpackage. 

So to do this, i delete  from the "go.mod" and "go.sum" the line that download the lorawan package, and then i add my edited lorawan package to /usr/local/go/source/github.com/brocaar, and finally i compil the project.

But  the compiler download again the lorawan package in my Gopath => /opt/go/package/mod/github.com/brocaar" and ignor my edited lorawan package, i also see that  the "go.mod" and "go.sum"  have again the line that search lorawan package.

I don't understand why he ignor my package and regenerat line that i delete from the "go.mod" and "go.sum", can some one help me, to force the go compiler to find my package lorawan in /usr/local/go/source/github.com/brocaar ?

my project is on => /opt/go/src/github.com/brocaar/lora-app-server

go version go1.13.3 linux/amd64

Go env : 
GO111MODULE=""
GOARCH="amd64"
GOBIN="/opt/go/bin"
GOCACHE="/home/jj/.cache/go-build"
GOENV="/home/jj/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/opt/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""

maybe the GO111MODULE soulde be in auto ?

**Comment by brocaar** [comment]
I'm closing this issue. I think this is more a general Go modules question. This wiki might be helpful to understand Go modules: https://github.com/golang/go/wiki/Modules
