### ISSUE TITLE
[Feature request] Device profiles across organizations

### ISSUE THREAD

**Issue by demetz** [brocaar/chirpstack-application-server#395]
Hi,

we are using the chirpstack (great new name!) for managing multiple organizations. We typically deploy the same sensors / LoRa devices for our clients, resulting in the same device profile in multiple organizations.

Unfortunately, currently we need to setup the "same" device profile individually for each organization. A great enhancement would be if the same device profile could be used by every organization.

Suggestion: in the global settings (e.g. next to Gateway Profiles) have another section called "global device profiles". When a user creates a new device for his organization, he would then be able to select either a device profile specifc to his organisation or a globally available device profile.

Is this an issue only we occur or could this be of interest to more users?

**Comment by brocaar** [comment]
Thanks for your suggestion. However I'm not planning to support this as this will make the data-structure and API authentication more complex as there are two ways a device can be linked to a device-profile.
