### ISSUE TITLE
nsec accuracy gone when using HTTP integration

### ISSUE THREAD

**Issue by nkostis** [brocaar/chirpstack-application-server#399]
it's been touched upon in other threads but i haven't seen this exact question.

I have GPS locked and working properly and i am indeed getting fine location *and* fine timestamps in the payload in loraserver UI:

![image](https://user-images.githubusercontent.com/1206818/70718281-9970e000-1cf8-11ea-9d12-b15cd9f4723c.png)

i've set up an HTTP integration where the same packet gets transmitted as this JSON:

![image](https://user-images.githubusercontent.com/1206818/70723153-1acc7080-1d01-11ea-8df2-b5a6ab65cd13.png)

the nanosecond accuracy timestamp is gone, the only one i get is the lower accuracy one (and they also have a 1 sec diff, which in another thread is attributed to leap seconds though i am not so sure).

the whole project is to triangulate the source device so GPS and nsec accuracy is crucial, is there a way to get it? (i mean apart from rebuilding  the app server ourselves!)

**Comment by brocaar** [comment]
I think using the `marshaler="json"` should solve the issue (v3.6.0+ https://www.chirpstack.io/application-server/install/config/). 

```
  # Integration configures the data integration.
  #
  # This is the data integration which is available for all applications,
  # besides the extra integrations that can be added on a per-application
  # basis.
  [application_server.integration]
  # Payload marshaler.
  #
  # This defines how the MQTT payloads are encoded. Valid options are:
  # * protobuf:  Protobuf encoding
  # * json:      JSON encoding (easier for debugging, but less compact than 'protobuf')
  # * json_v3:   v3 JSON (will be removed in the next major release)
  marshaler="json_v3"
```

This should give you the same `rxInfo` as that you are seeing in the web-interface. Please note that this JSON format is not compatible, but this will become the default in the next major release.
