### ISSUE TITLE
FUOTA does not complete

### ISSUE THREAD

**Issue by darkfader** [brocaar/chirpstack-application-server#401]
### Is this a bug or a feature request?
bug

### What did you expect?
completion (ok or error) of firmware job.

### What happened?
Session halted at state MC_SESS_C_SETUP.
Also, I see a ridiculous timeout value in the appserver.
"Multicast timeout | 1073741824 seconds" (hmm.. 0x40000000)
But I send "multicastTimeout": 30,

I can now create multiple jobs even if the previous jobs did not complete yet. This may throw off the schedule?

### What version are your using?
I dunno. The latest chirpstack-docker.

### How can your issue be reproduced?
I created fuotaDeployment via API. Perhaps start multiple jobs for one device.

### Desired fix
- fix the multicast timeout.
- an option to cancel/delete firmware jobs.
- perhaps a better indication of device state in the job overview. (number of devices in PENDING, ERROR, ...).

**Comment by brocaar** [comment]
FUOTA has been refactored into https://github.com/brocaar/chirpstack-fuota-server
