### ISSUE TITLE
chirpstack-application-server http2Server.HandleStreams received bogus greeting from client

### ISSUE THREAD

**Issue by silent123go** [brocaar/chirpstack-application-server#406]
### Could you share your log output?
1月 01 11:03:08 jimmy chirpstack-application-server[530]: time="2020-01-01T11:03:08+08:00" level=warning msg="grpc: Server.Serve failed to create ServerTransport:  connection error: desc = \"transport: http2Server.HandleStreams received bogus greeting from client: \\\"GET / HTTP/1.1\\\\r\\\\nHost: lo\\\"\""

**Comment by brocaar** [comment]
I'm closing this issue as there is no way I can reproduce this with the provided information.
