### ISSUE TITLE
Link a LocationEvent to one or more UplinkEvents

### ISSUE THREAD

**Issue by diversit** [brocaar/chirpstack-application-server#413]
### Is this a bug or a feature request?

Feature

### What did you expect?

It would be nice to be able to link a LocationEvent to one or more (in case of multi-frame geolocation) UplinkEvents. This would allow to specifically track back which frames caused a geolocation lookup.

Currently an UplinkEvent has 'uplinkID's for each gateway which received the message, but the message itself does not have a unique identifier. If such an identifier could be added, then this identifier could be added to the LocationEvent to indicate which frames caused the geolocation lookup. 

### What happened?

Currently LocationEvent has no reference to an UplinkEvent and UplinkEvent has no unique identifier.

### What version are your using?

3.6.1

**Comment by brocaar** [comment]
I'm planning to add a `uplink_ids` field to the location events. I believe that should make it possible to link the location event against the uplink meta-data.

```proto
    // Uplink IDs used for geolocation.
    repeated bytes uplink_ids = 7 [json_name = "uplinkIDs"];
```
