### ISSUE TITLE
Application Server UI is not using relative paths

### ISSUE THREAD

**Issue by Torsten1981** [brocaar/chirpstack-application-server#414]
One can not host the application server ui within a subroute of a domain, e.g. https://my-intra.net/chirpstack, due to the site is using absolute url path referencing domain root "/*".

The result of hosting within a sub route is that the Start Page is reachable, but remains empty/white. As I can see within Chrome developer tools F12, wihin HTML Code, there are absolute URL Paths to load extra content without my chosen sub route “/chirpstack”.
The Page tries to load CSS and JS from “/static/js” and not from “/chirpstack/static/js”, naturally this fails.
The expected behaviour would be, that the ui uses relative paths for links, src of css and scripts as well as for api calls and as result can be hosted within a sub route of domain root, e.g. https://my-intra.net/chirpstack

**Comment by brocaar** [comment]
This is not supported currently. If one would like to implement this, I would welcome a pull-request :)
