### ISSUE TITLE
possible rights conflict using device profiles

### ISSUE THREAD

**Issue by TestingMandy** [brocaar/chirpstack-application-server#415]
### Is this a bug or a feature request?
bug

### What did you expect?
* error message on creating the device
* same behavior of websites and api

### What happened?
On creating a new device via api, it is possible to assign a device profile from another organization. Those devices can be created by users, which are admin in serveral organizations.
On creating a device on the server website, device profiles from other organizations are not available in the drop down menu.

Users, that do not know the device profile due to rights are not able to show the detail device webpage. Those devices are listed in the device overview on the server websites, but on clicking on them the login prompt is shown, without any notification or error message for users. 

### What version are your using?
application-server: 3.6.1

### How can your issue be reproduced?
Create a device via api in organization A, but assign a device profile from organization B. 
A user, which is only in organization A admin, clicks in device overview on the created device.

**Comment by brocaar** [comment]
The above commit fixes this issue (+ adds a test for this).
