### ISSUE TITLE
ADD objectJSON data to the uplink window(line), under DEVICE DATA tab into Application/app/Devices/dev page

### ISSUE THREAD

**Issue by ric2498** [brocaar/chirpstack-application-server#422]
### Is this a bug or a feature request? 
feature request

### What did you expect?
Could we add the objectJSON data to the the uplink window(line) ? ; it will eliminate the needs to open the line to see the objectJSON data

### What happened?
n/a
### What version are your using?
3.7.0

### How can your issue be reproduced?
n/a

### Could you share your log output?
n/a

**Comment by brocaar** [comment]
I'm not sure if this would look well, as the `objectJSON` could contain multiple (nested) items. Could you share how you think this should look like?

**Comment by ric2498** [comment]
Hi,

Thanks Orne,

You will find into this pdf file the way I think it could look.

Richard.

**Comment by sophiekovalevsky** [comment]
@ric2498 it looks like pdf is missing.

**Comment by ric2498** [comment]
sorry you should have it now.
