### ISSUE TITLE
DNS name does not exist. (code: 14)

### ISSUE THREAD

**Issue by sagar-patel-sls** [brocaar/chirpstack-application-server#426]
I have downloaded .exe file from below URL
https://www.chirpstack.io/application-server/overview/downloads/

1. started chirpstack-network-server using CMD
2. using CMD I am starting chirpstack-application-server and it started perfectly but when access ui from browser it will throw below error

`error parsing service config: error from DNS TXT record lookup: lookup _grpc_config.localhost: dnsquery: DNS name does not exist. (code: 14)`

there is no logs available in chirpstack-application-server.
![image](https://user-images.githubusercontent.com/43664335/74738449-f222a300-527c-11ea-86ab-877900d4816c.png)

**Comment by sagar-patel-sls** [comment]
Hii @brocaar ,

we have solved this `error parsing service config` error 

we have updated the `gRPC` version in `go.mod` file 
~~google.golang.org/grpc v1.26.0~~ 
google.golang.org/grpc v1.27.0

https://github.com/grpc/grpc-go/releases/tag/v1.27.0

Please review this change...

**Comment by brocaar** [comment]
Awesome, thanks for testing this :+1:
