### ISSUE TITLE
UI search broken in 3.8.0-8-g6a0a81b

### ISSUE THREAD

**Issue by istina-iot** [brocaar/chirpstack-application-server#428]
### Is this a bug or a feature request?
Bug or new feature?
### What did you expect?
UI search worked
### What happened?
UI search broken
### What version are your using?
3.8.0-8-g6a0a81b
### How can your issue be reproduced?
install docker and try search
### Could you share your log output?
![image](https://user-images.githubusercontent.com/59253021/74920220-e0581180-53dc-11ea-8e37-9ac38ebfd406.png)

**Comment by istina-iot** [comment]
Same bug 3.8.0-9-g0159378

**Comment by brocaar** [comment]
Thanks for reviewing this so quick. I know, I'm checking the wrong field. The input should not be empty instead of the target. Fixing this now.

**Comment by istina-iot** [comment]
3.8.0-11-g477367e - ok
Thanks!
