### ISSUE TITLE
Cant send messages

### ISSUE THREAD

**Issue by Snotmann** [brocaar/chirpstack-application-server#431]
Cant sent messages due to downlink queue:

Feb 28 12:51:44 lorawangw chirpstack-network-server[464]: time="2020-02-28T12:51:44+01:00" level=error msg="schedule next device-queue item error" ctx_id=cd8db32d-2c6c-4361-9cc4-f5143f5b6456 dev_eui=0018b2000002116e error="get device gateway RXInfoSet error: object does not exist"
Feb 28 12:51:45 lorawangw chirpstack-network-server[464]: time="2020-02-28T12:51:45+01:00" level=error msg="schedule next device-queue item error" ctx_id=fc92b61c-d358-42c7-a730-053d1c78e5d1 dev_eui=0018b2000002116e error="get device gateway RXInfoSet error: object does not exist"
Feb 28 12:51:46 lorawangw chirpstack-network-server[464]: time="2020-02-28T12:51:46+01:00" level=error msg="schedule next device-queue item error" ctx_id=30df10d6-ea52-4f54-b886-9c6942c256a4 dev_eui=0018b2000002116e error="get device gateway RXInfoSet error: object does not exist"
Feb 28 12:51:47 lorawangw chirpstack-network-server[464]: time="2020-02-28T12:51:47+01:00" level=error msg="schedule next device-queue item error" ctx_id=ba278ae8-a93f-4ef7-81df-629d7a2f2d2f dev_eui=0018b2000002116e error="get device gateway RXInfoSet error: object does not exist"
Feb 28 12:51:48 lorawangw chirpstack-network-server[464]: time="2020-02-28T12:51:48+01:00" level=error msg="schedule next device-queue item error" ctx_id=6c359895-ae89-408e-9bff-2aa365f4db4d dev_eui=0018b2000002116e error="get device gateway RXInfoSet error: object does not exist"

I got a LoRa HAT on my raspberry and a multitech gateway. I receive data from them but cant sent messages ...

Dont know why ?!

Snot

**Comment by brocaar** [comment]
I'm closing this issue. For community support, please see https://forum.chirpstack.io.
