### ISSUE TITLE
Same device address for different devices

### ISSUE THREAD

**Issue by TestingMandy** [brocaar/chirpstack-application-server#437]
### Is this a bug or a feature request?
bug

### What did you expect?
error message on assigning activation settings for a device, when the device address is already used by another device

### What happened?
It is possible to create devices, whose have different device EUIs but same activation settings (device address, network session key, application session key).

It should not be the responsibility of the user to know all other settings. 
Especially users, that do not know all devices due to rights are not able to check already existing device addresses.

### What version are your using?
application-server: 3.6.1

### How can your issue be reproduced?
Create a device with activation settings like an already available device.

**Comment by brocaar** [comment]
> Same device address for different devices 
> error message on assigning activation settings for a device, when the device address is already used by another device

This is perfectly valid as the DevAddr space is smaller than the DevEUI space. It is not unlikely that two devices are sharing the same DevAddr. The ChirpStack Network Server is able to handle this as it will validate the MIC using the session-keys of each DevEUI linked to the DevAddr.
