### ISSUE TITLE
Is it possible to add BASE_PATH to  Application server 

### ISSUE THREAD

**Issue by raghurags** [brocaar/chirpstack-application-server#448]
### Is this a bug or a feature request?

Is it possible to add BASE_PATH to  Application server. If it is  yes, how to add Base-path!
Because i need to deploy in Nginx Kubernetes so need base-path.

**Comment by brocaar** [comment]
This is not supported.

**Comment by mrauter** [comment]
would also need this feature, maybe it comes on the list
