### ISSUE TITLE
Cannot use multiple network servers

### ISSUE THREAD

**Issue by darkfader** [brocaar/chirpstack-application-server#450]
### Is this a bug or a feature request?
bug

### What did you expect?
that multiple network servers can work

### What happened?
I created two network servers. they have ID 1 and 8.
When creating a gateway, in the network-server dropdown, ONLY the first is displayed.
So, when I continue, data is always sent via my first (EU868) network server.

### What version are your using?
3.9.0

### How can your issue be reproduced?
I created two gateway bridges, two redis server, two databases on one postgresql server,  two mosquittos (but only 1 can be configured in the application server?!), one application server.
I can't change it via the API either.

### Could you share your log output?
I can see join requests, but the join accept is sent on the same frequency (if I have 1 mosquitto I guess. which works for EU868). But the one I want to get working is a US915 configured gateway which should be sent out on different frequency.

gateway error log on US915 gateway when trying to respond to my EU868 and US915 nodes:
Packet REJECTED, unsupported frequency - 902700000 (min:923000000,max:928000000)
Packet REJECTED, unsupported frequency - 869525000 (min:923000000,max:928000000)

**Comment by brocaar** [comment]
You need to create a service-profile first to connect an organization with a network-server :) (each SP connected to a single NS).
