### ISSUE TITLE
FUOTA for multiple devices

### ISSUE THREAD

**Issue by victordemin** [brocaar/chirpstack-application-server#468]
I am very interesting in FUOTA service. For one device in class C everything is work ok. But i need multiple devices firmware update in class B. When this feature could be implemented?

**Comment by cblack-sve** [comment]
Is multicast and Class B even compatible? @brocaar 
We are also looking into creating a script or maybe even a branch to implement multiple device fuota (for class C, though)

**Comment by brocaar** [comment]
FUOTA has moved to: https://github.com/brocaar/chirpstack-fuota-server.
