### ISSUE TITLE
Include hover at list table views. 

### ISSUE THREAD

**Issue by sophiekovalevsky** [brocaar/chirpstack-application-server#471]
- [x] I have searched the [issues](https://github.com/brocaar/chirpstack-application-server/issues) of this repository and believe that this is not a duplicate.

## Summary

Whenever someone passes the mouse pointer over a row table at any given list view, fire up an hover change in color for that particular row.  

## What is the use-case?

ChirpStack Application Server allows to play with how many entries will be seen per row. When the ratio rows per page increases there will be more elements in one single view. I think a good asset to improve user experience would be to highlight the row entry to which the user wants to inspect.

Another use case can be ilustrated e.g. if you want to cross Device Name with it's respective battery value. You will need to guide your eye almost to end of the row, which can be difficult to follow if there is no tool to help you to highlight it. 

## Implementation description

The following gif represents how the user will feel this at front-end level using the Device List Table.

![hover-table](https://user-images.githubusercontent.com/1287883/79874531-da6fb400-83be-11ea-99c6-3c0cc22ef10f.gif)

The front-end changes would be a React Js component, adding **hover** to each TableRow instance. 

## Can you implement this by yourself and make a pull request?
Yes, I do.

**Comment by brocaar** [comment]
Sounds good to me! :-) :+1: 

I guess that would be using this option?

![image](https://user-images.githubusercontent.com/165497/80613181-38467080-8a3d-11ea-8061-5760aa948a1d.png)

**Comment by sophiekovalevsky** [comment]
Yeah, that's right.  I will prepare changes this week :)

**Comment by sophiekovalevsky** [comment]
- Row tables that are not listing items with row per page such as Details at DeviceDetails were not taken into consideration in this feature.
