### ISSUE TITLE
Gateway with unknown coordinates stored in database with zero coordinates

### ISSUE THREAD

**Issue by wireless-road** [brocaar/chirpstack-application-server#473]
## What happened?
Gateway I created without setting its coordinates stored in `gateway` table of postgres database with zero coordinates.

```
loraserver_as=> select mac, longitude, latitude  from gateway;
        mac         | longitude | latitude 
--------------------+-----------+----------
 \xaa555a0000000006 |  37.86387 | 55.74557
 \xaa555a0000000005 |   37.8866 | 55.75458
 \xaa555a0000000007 |         0 |        0

```
## What did you expect?
I expect `longitude`, `latitude` fields of `gateway` table to be empty in such cases. 
## Steps to reproduce this issue

Steps:

1. Create gateway using `chirpstack-application server` without setting its coordinates.
2. Connect to posgres database: 
```
docker exec -it lora_postgres psql -U loraserver_as
```
3. Check that gateway registered on first step stored with zero coordinates: 
```
select mac, longitude, latitude  from gateway;
```

## Your Environment
Docker containers based `chirpstack`

Not sure that it is a bug at all so just letting you know. We faced such issue during development additional micro service that display gateways on map. So gateway without coordinates gonna be displayed on latitude/longitude 0.00/0.00. To avoid that behaviour we are handling such cases on front side.

**Comment by brocaar** [comment]
These fields are `not null` in the schema. This avoids dealing with pointers in the Go code. The result is that fields that are not set, will be set to their default values, e.g. `string` will be an empty string, `int` and float types will be `0`, etc...
