### ISSUE TITLE
Redis is loosing Device Activation data

### ISSUE THREAD

**Issue by Niondir** [brocaar/chirpstack-application-server#488]
- [x ] The issue is present in the latest release.
- [x ] I have searched the [issues](https://github.com/brocaar/chirpstack-application-server/issues) of this repository and believe that this is not a duplicate.

## What happened?
I'm not sure if it's directly related to Chirpstack or just an Issue with Redis. But on a raspberry PI where the Redis is mounted on an external SSD I'm loosing all redis data is some cases.

It's hard to reproduce and I have no logs yet. but any thoughts to find or fix the issues would help.

## What did you expect?
Never loose activation data from devices.

## Steps to reproduce this issue
Not sure.

## Could you share your log output?
No
## Your Environment

| Component           | Version |
| --------------------| ------- |
| Application Server  | v?.?.?  |
| Network Server      |         |
| Gateway Bridge      |         |
| Chirpstack API      |         |
| Geolocation         |         |
| Concentratord       |         |

**Comment by brocaar** [comment]
This is not a ChirpStack issue. Please refer to https://redis.io/topics/persistence about persisting Redis data.
