### ISSUE TITLE
Incorrect decryption of sensor payload in live view

### ISSUE THREAD

**Issue by loffa** [brocaar/chirpstack-application-server#489]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/brocaar/chirpstack-application-server/issues) of this repository and believe that this is not a duplicate.

## What happened?
Sensors joined using OTAA does not get the payload decrypted properly in the web interface. The installation of Chirpstack is run inside of kubernetes with configuration from the docker-compose example.

An encrypted package was captured on the gateway, before sending to gateway-bridge. That package was decrypted using [this website](https://lorawan-packet-decoder-0ta6puiniaut.runkit.sh/). The app-session-key and network-session-key was copied over from Application Server Web Interface. The decrypted payload in the package did not match the payload as shown in Live frames in Chirpstack for that device (after base64 decoding). It seems like the decryption of the payload is not done properly in the UI. This has been working on other systems as a way to capture data and send for debugging. The data published by the application-server in the JSON payload is correctly decrypted for use in applications.

payload encrypted: `QGohkgCAEgAUZ0VxIQjrBQ==`
app-session-key: `2b57b5877678433b75392a80b7d5693f`
net-session-key: `7cf132dd2b510fb0b35be92079d63392`

Chirpstack Live frame payload bytes (b64): `Z0Vx`

Binary data as follows (hex):
Web Decoder - `0x01 0x00 0x04`
Base64 Deocded chirpstack payload - `0x67 0x45 0x71`

## What did you expect?
I expected the payload to be decrypted correctly and the data to be in a non encrypted form.

## Could you share your log output?
I don't know what logs I can get to help.

## Your Environment
| Component           | Version |
| --------------------| ------- |
| Application Server  | v3.10.0 |
| Network Server      | v3.9.0 |
| Gateway Bridge      | v3.8.0 |
| Chirpstack API      | n/a |
| Geolocation         | n/a |
| Concentratord       | n/a |

**Comment by brocaar** [comment]
> The decrypted payload in the package did not match the payload as shown in Live frames in Chirpstack for that device (after base64 decoding).

ChirpStack does not decrypt the LoRaWAN frames:
![image](https://user-images.githubusercontent.com/165497/84502790-47197780-acb9-11ea-92bd-fd43ae4567e9.png)

The data under Device data **is** decrypted.
