### ISSUE TITLE
Add sticky header on tables 

### ISSUE THREAD

**Issue by sophiekovalevsky** [brocaar/chirpstack-application-server#491]
- [x] I have searched the [issues](https://github.com/brocaar/chirpstack-application-server/issues) of this repository and believe that this is not a duplicate.

## Summary

When someone is navigating over a table, it may happen that the records can reach up to 500 per page. If this happen, as the user scrolls down it will lost visibility of header cells. I propose to take advantage of sticky header at tables so that users can scroll down and still maintain header visibility. 

## What is the use-case?

The use case will apply for all existing tables. The most common use case would be when someone is listing Devices. 

Another use case would be when someone resize the screen, this is what actually happens: 

![image](https://user-images.githubusercontent.com/1287883/84668445-078d9e00-aefa-11ea-89c0-b51ea4d36fdf.png)

With this feature we can wrap the records within the table container so that user can scrolls to the right and see the records in a cleaner way. Like this: 

![image](https://user-images.githubusercontent.com/1287883/84668796-6ce18f00-aefa-11ea-8f0a-976d2a577f47.png)

## Implementation description

![sticky-header](https://user-images.githubusercontent.com/1287883/84667041-3440b600-aef8-11ea-9416-b18014e34bd1.gif)

Material UI already provides tools to enable this using adding [`stickyHeader aria-label="sticky table"`](https://material-ui.com/api/table/) to `Table` component and adding [`TableHead`](https://material-ui.com/api/table-head/). 

## Can you implement this by yourself and make a pull request?
Yes, I can.

**Comment by brocaar** [comment]
Would the height of the table automatically match the remaining height of the screen? It looks like in your example you first scroll down to see the bottom of the table and then you scroll through the table.

**Comment by sophiekovalevsky** [comment]
@brocaar, right now the height does not adjust to the high of the screen, a max. height is being used instead.

The effect that happens on the animation is because the height of the main page exceeds the height of my screen. What I can try to dois  match the height of the table with the height of the current screen. Does this make sense to you?

**Comment by brocaar** [comment]
Thanks @sophiekovalevsky. to be honest, I'm not sure if I would be in favor of this feature. This would require a couple of "tricks" to make this work properly and I'm not sure if it will be worth the effort.

**Comment by sophiekovalevsky** [comment]
@brocaar, all right. Thanks for letting me know.
