### ISSUE TITLE
Failed Build with docker

### ISSUE THREAD

**Issue by symovs** [brocaar/chirpstack-application-server#497]
Hi

I tried to build the source code with docker using the command given in documentation 

docker-compose run --rm chirpstack-application-server bash

But it failed with the following error. Please help. I am using the latest cloned version of the application source file from Github. 

![image](https://user-images.githubusercontent.com/66220236/85941205-1a16c700-b93f-11ea-93bb-434dd719f4f0.png)

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/brocaar/chirpstack-application-server/issues) of this repository and believe that this is not a duplicate.

## Steps to reproduce this issue

Steps:

1.
2.
3.
4.

## Could you share your log output?

```shell

```

## Your Environment

| Component           | Version |
| --------------------| ------- |
| Application Server  | v?.?.?  |
| Network Server      |         |
| Gateway Bridge      |         |
| Chirpstack API      |         |
| Geolocation         |         |
| Concentratord       |         |

**Comment by symovs** [comment]
I am trying to build on a Raspberry PI zero W with ARM V6 processor.

**Comment by brocaar** [comment]
Currently building the Docker image on ARM is not supported.
