### ISSUE TITLE
Device status in Influx not completed

### ISSUE THREAD

**Issue by Cheprod** [brocaar/chirpstack-application-server#499]
Hi,

We use Influxdb integration to track device uplink statistics.

In device_uplink measurement we have only one line by uplink even if two or more gateways receive the packet. So, we cant determinate if they're is redondancy between GW.

In the MQTT data, all the informations are presents and we actually record the MQTT data to diagnose links quality.

We also want to track Gateways statistics as geoloc informations by recording them in Influxdb database (A global one).

We are ready to help by developping Thib functionalities if needed.

Regards.
Thibaud

**Comment by brocaar** [comment]
> In device_uplink measurement we have only one line by uplink even if two or more gateways receive the packet.

I think it would be good to keep it this way, but maybe add a `gw_count` value to that?
