### ISSUE TITLE
[API] Make the search available for applications which use the api-keys

### ISSUE THREAD

**Issue by maxreb** [brocaar/chirpstack-application-server#510]
- [x] I have searched the [issues](https://github.com/brocaar/chirpstack-application-server/issues) of this repository and believe that this is not a duplicate.

## Summary

Currently the global search is only availabe when logged in as user. I assume this is because it is marked as internal. Is it possible to make the search also available for applications which use the api-key? 

## What is the use-case?

One example use is that I want to know the company name of a device. Currently this looks like this: `Get Application ID from EUI -> Get Company ID from Application ID -> Get Company Name from Company ID` Within a global search this could all fit in one api call. Another example is if we want to search in the software which uses the API like we do on the chirpstack application server without the reqiuerment of the user to log in (again).

## Can you implement this by yourself and make a pull request?
I could try if its wanted

**Comment by brocaar** [comment]
I don't think this is a good idea. As you mentioned this is for internal use to facilitate the web-interface. These endpoints can change over time in an incompatible way and your integrations would break.
