### ISSUE TITLE
AutocompleteSelect no longer shows a placeholder value

### ISSUE THREAD

**Issue by End-S** [brocaar/chirpstack-application-server#524]
- [x ] The issue is present in the latest release.
- [x ] I have searched the [issues](https://github.com/brocaar/chirpstack-application-server/issues) of this repository and believe that this is not a duplicate.

## What happened?
Select controls in the UI no longer display their placeholder values.
## What did you expect?
A place holder value to appear in the select control until a value is selected by the user
## Steps to reproduce this issue
Go to any implementation of AutocompleteSelect in the UI and see that the placeholder is no longer visible. 
For example:
1. Go to Device-profiles
2. Select Create
3. The "Network-server" select does not display the placeholder value of "Select network-server" as it should

## Potential Solution
A fix for this is to add a `placeholder` property to the `<TextField>` in `AutoCompleteSelect.js`:
```javascript
<Autocomplete
  id={this.props.id}
  options={this.state.options}
  getOptionLabel={(option) => option.label || ""}
  onOpen={() => this.setInitialOptions(null)}
  openOnFocus={true}
  value={this.state.selectedOption || ""}
  onChange={this.onChange}
  onInputChange={this.onInputChange}
  className={this.props.className}

  renderInput={(params) => <TextField required={!!this.props.required} placeholder={this.props.label} {...params} /> }

  disableClearable={!this.props.clearable}
/>
```
I have used the `label` prop, as this appears to be what the placeholder has been assigned to in the past.

If this solution is satisfactory I can create a PR.

| Component           | Version |
| --------------------| ------- |
| Application Server  | v3.11.1  |

**Comment by brocaar** [comment]
Hi @End-S, yes please create a pull-request for this :)
