### ISSUE TITLE
POST /api/gateway-profiles fails with 401

### ISSUE THREAD

**Issue by onsolutionjames** [brocaar/chirpstack-application-server#525]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/brocaar/chirpstack-application-server/issues) of this repository and believe that this is not a duplicate.

## What happened?
When I do a POST request to /api/gateway-profiles I get a 401 error. This only happens when using an API key generated through the 'API keys' screen, and not when using the API key that the browser uses. 

I am able to use the same API key to make other API requests successfully

## What did you expect?
I expect to be able to use this API endpoint when using a generated API key

## Steps to reproduce this issue

Steps:

1. Generate an API key through the 'API keys' screen
2. Attempt to make a POST request to /api/gateway-profiles

## Could you share your log output?

Request through Swagger:

```
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Grpc-Metadata-Authorization: Bearer <<secret>>' -d '{ \
    "gatewayProfile": { \ 
        "name": "profilename", \ 
        "channelsStr": "0,1,2,3,4,5,6,7,64", \ 
        "channels": [0, 1, 2, 3, 4, 5, 6, 7, 64], \ 
        "networkServerID": "9" \ 
    } \ 
}' 'http://192.168.20.8:8080/api/gateway-profiles'
```

Response:

```
{
  "error": "authentication failed: not authorized",
  "code": 16,
  "message": "authentication failed: not authorized",
  "details": []
}
```

Shell output: 
```shell
INFO[0009] finished unary call with code Unauthenticated  ctx_id=3ea5c5c5-851f-4942-a303-c512889a4a59 error="rpc error: code = Unauthenticated desc = authentication failed: not authorized" grpc.code=Unauthenticated grpc.method=Create grpc.service=api.GatewayProfileService grpc.start_time="2020-08-21T01:47:23Z" grpc.time_ms=1.753 peer.address="127.0.0.1:34008" span.kind=server system=grpc
```

## Your Environment 

Running on Ubuntu 18.04
Also achievable in Swagger.

| Component           | Version |
| --------------------| ------- |
| Application Server  | v3.11.1  |
| Network Server      | 3.10.0 |
| Gateway Bridge      | 3.9.2 |
| Chirpstack API      |         |
| Geolocation         |         |
| Concentratord       |         |

**Comment by brocaar** [comment]
Thanks for reporting @onsolutionjames. The above commit fixes this issue.
