### ISSUE TITLE
Error:”invalid MIC”

### ISSUE THREAD

**Issue by Shahboz0** [brocaar/chirpstack-application-server#528]
## What happened?
Hi,
I have problem with uplink, device joining by ABP.My frame counter is disabled,
screen of problem here
![fbf7b03737fbbaf26d8cbd6744c48b7d48f905b8_2_690x291](https://user-images.githubusercontent.com/44652698/92141528-3b060780-ee1b-11ea-8f7a-487775144c43.png)
in gateway I saw packets
![5a467db6294f22da900e564d5279f732eb219dd2_2_690x319](https://user-images.githubusercontent.com/44652698/92141577-4bb67d80-ee1b-11ea-9dee-280f4fddc679.png)
logs from network and application server show me no errors
![c46a13313261ae1fbad2fd6a370808c583a13d1a_2_690x135](https://user-images.githubusercontent.com/44652698/92141608-553fe580-ee1b-11ea-8e57-8d782a090846.png)
my device-profiles parameters
![47e59f10d9860eb2205c36467a742b6c108cb3d6_2_690x405](https://user-images.githubusercontent.com/44652698/92141654-638e0180-ee1b-11ea-970d-fa2bd6084ae0.png)
My configs here
https://github.com/brocaar/chirpstack-network-server/issues/494

**Comment by brocaar** [comment]
An invalid MIC means that the provided vs expected MIC do not match. Usually this means that your session-keys are invalid.r

**Comment by Shahboz0** [comment]
But sometimes I'm getting uplink packet without error
