### ISSUE TITLE
MAC commands logging(JoinReauest, JoinAccept, etc...)

### ISSUE THREAD

**Issue by golovlevviktor** [brocaar/chirpstack-application-server#535]
It will be great to have a responsibility to get information about MAC commands via MQTT interface - JoinAccepts, JoinRequests, StatusRequests, etc - It will give more information about network and it`s load.

For now it is possible to get this  information from live log, or parse protobuf messages from MQTT gateway/... topics

**Comment by brocaar** [comment]
> It will give more information about network and it`s load.

Could you clarify this?

In general I'm not sure if I would favor this, but I'm open for discussing this further.

**Comment by sagar-patel-sls** [comment]
@brocaar 
can we expose `LoRaAirtime` in uplink?

**Comment by brocaar** [comment]
I'm closing this issue. @sagar-patel-sls yes that would be possible, but it would be for a different GitHub issue :)
