### ISSUE TITLE
Add gateway downlink information in TxAck message

### ISSUE THREAD

**Issue by hoffi085** [brocaar/chirpstack-application-server#537]
- [ x] I have searched the [issues](https://github.com/brocaar/chirpstack-application-server/issues) of this repository and believe that this is not a duplicate.

## Summary

The downlink information could be added to the TxAckEvent message. The downlink information could be:

- Gateway EUI which has emitted the downlink
- Tx information: frequency, spreadingfactor, bandwidth, code rate, tx power [dBm]
- Metadata of Gateway
- ...

## What is the use-case?
Since the network server chooses the best gateway for downlink in a given margin (Downlink gateway randomization since version 3.8.0) adding the gateway and transmitt information to the TxAckEvent could help to find problems when sending downlinks to the device.

## Implementation description
Adding the gateway information in the TxAckEvent is the best place for this feature as recommended by @brocaar [here](https://forum.chirpstack.io/t/getting-gateway-eui-which-has-send-the-downlink/9236)

**Comment by sagar-patel-sls** [comment]
Hi, @brocaar 

I have implemented this feature and ready to make a pull request, but I would like to review the below screenshot of txinfo.

I have made changes in `chirpstack-api`, `chirpstack-network-server` and `chirpstack-application-server`

please find the below screenshot for your reference

**1. MQTT Integration TxAckEvent**
![txinfo_mqtt-integration](https://user-images.githubusercontent.com/43664335/103739367-89baec80-501b-11eb-94c6-6b072b25400c.jpeg)

**2. Device Data TxAck** 
![txack_device_data](https://user-images.githubusercontent.com/43664335/103739400-98090880-501b-11eb-9094-410732aa101a.jpeg)

@brocaar please review this change
Thanks

**Comment by sagar-patel-sls** [comment]
@brocaar any update?

**Comment by sagar-patel-sls** [comment]
Hii @brocaar 
any update on this issue?

**Comment by brocaar** [comment]
Sorry for the delay @sagar-patel-sls, I've had a really busy period past months supporting various projects. I'm now catching up with all the community requests and will now review your PR :)
