### ISSUE TITLE
undeletable admin user

### ISSUE THREAD

**Issue by shepiloff** [brocaar/chirpstack-application-server#538]
- [x] I have searched the [issues](https://github.com/brocaar/chirpstack-application-server/issues) of this repository and believe that this is not a duplicate.

## Summary

make default admin user undeletable

## What is the use-case?
in case of accidental of user deletion there are no users with admin priveleges and no users who can log in to UI

**Comment by sagar-patel-sls** [comment]
Hi @brocaar 

we cannot allow delete users themselves.

If you agree then I will make PR for this
Thanks

**Comment by brocaar** [comment]
Hi @sagar-patel-sls, I think making sure that users can't delete themselves would be better than making the default user undeletable :) I'm happy to review a PR for that!
