### ISSUE TITLE
The stats interval value in the Gateway-profile page does not show set value after saving

### ISSUE THREAD

**Issue by t0mmyz7** [brocaar/chirpstack-application-server#544]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/brocaar/chirpstack-application-server/issues) of this repository and believe that this is not a duplicate.

## What happened?

When I set gateway stats interval in the Gateway-profile, then save, the value remains empty.

## What did you expect?

The field should retain the set value of Gateway interval seconds

## Steps to reproduce this issue

Steps:

1. In the app server, browse to gateway-profile
2. Set a Stats interval value in seconds
3. Update gateway-profile
4. Re-enter the gateway profile page

using latest docker-compose stack

**Comment by brocaar** [comment]
Please see my comment on #546
