### ISSUE TITLE
ADR engine - on/off/"manual" : Please can we have the option to control end-device Mac settings in the Device Profiles area

### ISSUE THREAD

**Issue by Cloolalang** [brocaar/chirpstack-application-server#558]
**

- [ x] I have searched the [issues](https://github.com/brocaar/chirpstack-application-server/issues) of this repository and believe that this is not a duplicate.

## Summary

In Service profiles we can modify the ADR engine slightly with MAX/MIN data rate, and in Device profile we have MAX device EIRP.
Both if these seem to work with the ADR engine process.
It would also be good to be able to control  NbRep  as different networks experience various levels for packet-collision threat and packet loss of other reasons. According to the Semtech algorithm, the target is about 10%.
Anyway to be able to turn on/off this part of the engine would be very useful for testing and optimizing situations.
Ultimately it would also be very useful to (when ADR is disabled) actually set a specific SF and TX_power for a device (in the device profile page). ADR seems to mainly benefit public LoRaWan networks where stricter control is needed. Chirpstack could ideal for lab-networks and small private networks where all the end-devices would more carefully managed.
 

## What is the use-case?
Lab- test networks
Networks which can accept various levels of packet loss.

## Implementation description

In either the device or service profile UI page.

## Can you implement this by yourself and make a pull request?
Sorry not the skills

**Comment by Cloolalang** [comment]
Or as an alternative:
In the chirpstack-network-server.toml
a field:

disable NbRep = true

**Comment by brocaar** [comment]
I'm closing this issue. For lab testing, I suggest to use the ADR plugins which was recently introduced. I don't think it is a good idea to give all end-users the control over the used DR and TX Power as this might cause issues on multi-tentant deployments.
