### ISSUE TITLE
Report Coding Rate in MQTT uplink json

### ISSUE THREAD

**Issue by jpmeijers** [brocaar/chirpstack-application-server#566]
- [x] I have searched the [issues](https://github.com/brocaar/chirpstack-application-server/issues) of this repository and believe that this is not a duplicate.

## Summary

The metadata of the uplink message should contain all available metadata, including Coding Rate.

## What is the use-case?

This is important for monitoring the radio link. We have a couple of variables that affect the signal, or indicates the quality:
* SF, BW, TX power, CR
* RSSI, SNR

Most of these are reported, but CR has been left out.

## Implementation description

This information should be available at the Network Server. It should be passed on to the Application server and be exposed on the MQTT data feed.

## Can you implement this by yourself and make a pull request?

Unfortunately not

**Comment by brocaar** [comment]
This is already implemented, but you must configure the `json` marshaler option in the `chirpstack-application-server.toml` configuration file. Example `txInfo` element taken from the `up` event:

```
"txInfo":{"frequency":867700000,"modulation":"LORA","loRaModulationInfo":{"bandwidth":125,"spreadingFactor":11,"codeRate":"4/5","polarizationInversion":false}}
```
