### ISSUE TITLE
Issue in Semtech's tracker TLV parser when several tags are in a frame

### ISSUE THREAD

**Issue by Oliv4945** [brocaar/chirpstack-application-server#628]
- [x] The issue is present in the latest release.
- [ ] I have searched the [issues](https://github.com/brocaar/chirpstack-application-server/issues) of this repository and believe that this is not a duplicate.

## What happened?

The TLV parser is not working when there are several tag/length/value in one frame, resulting in DAS error.

ex: A GNSS NAV message provided to the DAS  `logmsg:"Ignore invalid GNSS message payload: 014d03e1c80ba22aa2ed12dd5f7c4459f1253c38889695e333af11dd9ce15a1d302a361d6f050d07100a28004d0e02"`

It is because another tag is included:

NAV message: `014d03e1c80ba22aa2ed12dd5f7c4459f1253c38889695e333af11dd9ce15a1d302a361d6f05`
2nd tag/length/value:  0d07100a28004d0e02

## What did you expect?

TLV correctly parsed if several are in one frame
The issue can be found in [this code](https://github.com/brocaar/chirpstack-application-server/blob/c83cd99f65bc111ec98e5f1af1f79e361eae7ad4/internal/integration/loracloud/loracloud.go#L671) when the frame is not parsed as a TLV: only the first byte is tested and length is never used.

## Your Environment

ns.loracloud.com

**Comment by brocaar** [comment]
Thanks for reporting @Oliv4945, the above commit should fix this issue.
