### ISSUE TITLE
Is there an API to obtain the correspondence between all devices and all gateways

### ISSUE THREAD

**Issue by Z-J-X** [brocaar/chirpstack-application-server#653]
Is there an API to obtain the correspondence between all devices and all gateways.
At present, the only way I can get the information between the device and the gateway is to read redis.Due to the different storage of objects in different languages, there is no way to directly restore objects in redis. At present, I analyze them according to the structure law of binary data in redis,but this is not a long-term solution.I hope to provide corresponding API interfaces to obtain this data,I hope to provide corresponding API interfaces to obtain this data.Or can the data be reflected in redis in the form of JSON or msgpack
the data in redis:
'lora:ns:device:000000624798ef25:gwrx':'0a08000000624798ef2510051a240a08aa5020210818000310b1ffffffffffffffff01199a99999999992b4032045e3e0279'

**Comment by brocaar** [comment]
There is currently no API that provides this information. Please see this function for an example how to read the value stored in Redis:

https://github.com/brocaar/chirpstack-network-server/blob/a133c4dc7a10c6abb99969c6092cc42a20d966f0/internal/storage/device_session.go#L598
