### ISSUE TITLE
chirpstack-application-server  clear device information ！！！

### ISSUE THREAD

**Issue by zgz757183190** [brocaar/chirpstack-application-server#673]
Hi  God, 
    under what circumstances will the chirpstack-application-server empty the "Device address" and "Network session key" and "Application session key" of the device.

Recently, this has always happened in my project, but I can't find the reason.

Device-profiles :  Class-C

AS   3.8
NS   3.8 
GW 3.8

**Comment by liangyuanpeng** [comment]
I don't think that the AS will clean this infomation.

**Comment by eydonmlau** [comment]
It's about device session expiration, you can checkout the device_session_ttl value.
[https://forum.chirpstack.io/t/device-address-missing-and-downlink-issue/7886](Refer this)

**Comment by liangyuanpeng** [comment]
> It's about device session expiration, you can checkout the device_session_ttl value in network server .toml.

Thanks for your confirm that, i really need to check my production environment for it.

**Comment by creyD** [comment]
@zgz757183190 Any update on this? Otherwise this ticket could be closed.
