### ISSUE TITLE
HTML file not found

### ISSUE THREAD

**Issue by zgz757183190** [brocaar/chirpstack-application-server#680]
Hi God!
 
	AS ---> Project started, HTML file not found!!!

	Download the source code and start it：
	“..\..\static\static.go:6:75: pattern *.html: no matching files found ”。

	Is there any document missing from this？ 

	Run Environment:
		goland/idea
		
		
thinks！

**Comment by sagar-patel-sls** [comment]
Hi @zgz757183190 
Please run the below command for `UI`.

`make ui-requirements`
`make statics`

**Comment by zgz757183190** [comment]
> 

think you !
