### ISSUE TITLE
How can I integrate HTTP with chirpstack? The link https://www.chirpstack.io/docs/chirpstack/integrations/http.html  provides the code, but are there any instructions to use this code in chirpstack? Basically using the HTTP integration feature, I need to retrieve the data sent by the end devices and store it in a file. 

### ISSUE THREAD

**Issue by Preety09-cmd** [brocaar/chirpstack-application-server#721]
- [ ] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/brocaar/chirpstack-application-server/issues) of this repository and believe that this is not a duplicate.

## Steps to reproduce this issue

Steps:

1.
2.
3.
4.

## Could you share your log output?

```shell

```

## Your Environment

| Component           | Version |
| --------------------| ------- |
| Application Server  | v?.?.?  |
| Network Server      |         |
| Gateway Bridge      |         |
| Chirpstack API      |         |
| Geolocation         |         |
| Concentratord       |         |

**Comment by brocaar** [comment]
The code explains how you can create an application which accepts data from ChirpStack. If you want to write data to a file, you need to make modifications to the code example to open a file, and write every incoming request to it.
